# Generated by Django 5.0.4 on 2024-08-22 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWithProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_zh', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group_with_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name_zh', models.CharField(blank=True, max_length=100, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'db_table': 'group_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='groupprofile',
            constraint=models.UniqueConstraint(fields=('name_zh', 'group', 'deleted_at'), name='unique_group_name_deleted_at'),
        ),
    ]
