# Generated by Django 5.0.4 on 2024-09-10 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupWithProfile',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
