# Generated by Django 5.0.4 on 2024-06-21 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='顯示順位')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='菜單名稱')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='菜單路由名稱')),
                ('path', models.CharField(blank=True, max_length=50, verbose_name='菜單路由路徑')),
                ('component', models.CharField(blank=True, max_length=50, verbose_name='菜單路由組件')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='菜單圖案')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu')),
            ],
            options={
                'db_table': 'menus',
                'ordering': ['priority'],
            },
        ),
    ]
