# Generated by Django 5.0.4 on 2024-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_menu',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否為菜單'),
        ),
        migrations.AddField(
            model_name='menu',
            name='meta',
            field=models.JSONField(blank=True, null=True, verbose_name='前端路由設定'),
        ),
    ]
