# Generated by Django 5.0.4 on 2024-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_component_alter_menu_icon_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='redirect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='跳轉路徑'),
        ),
    ]
