# Generated by Django 5.0.4 on 2024-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_redirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meta',
        ),
    ]
