# Generated by Django 5.0.4 on 2024-06-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_menu_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=50, unique=True, verbose_name='菜單路由名稱'),
        ),
    ]
