# Generated by Django 5.0.4 on 2024-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, default='component', max_length=50, unique=True, verbose_name='菜單路由組件'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, default='path', max_length=50, unique=True, verbose_name='菜單路由路徑'),
        ),
    ]
