# Generated by Django 5.0.4 on 2024-06-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_menu_component_alter_menu_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_disabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否停用'),
        ),
    ]
