# Generated by Django 5.0.4 on 2024-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groupprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWithProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=150)),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'group_with_profile',
                'managed': False,
            },
        ),
    ]
