# Generated by Django 5.0.4 on 2024-06-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupprofile_is_deleted_alter_groupprofile_name_zh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='is_deleted',
        ),
    ]
