# Generated by Django 5.0.4 on 2024-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_groupprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
