# Generated by Django 5.0.4 on 2024-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0007_groupprofile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='groupprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name_zh', 'group'), name='unique_group_name_not_deleted'),
        ),
    ]
