# Generated by Django 5.0.4 on 2024-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_groupprofile_name_zh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
