# Generated by Django 5.0.4 on 2024-08-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0009_groupprofile_deleted_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupprofile',
            name='unique_group_name_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='groupprofile',
            constraint=models.UniqueConstraint(fields=('name_zh', 'group', 'deleted_at'), name='unique_group_name_deleted_at'),
        ),
    ]
