# Generated by Django 5.0.4 on 2024-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='record_date',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=1, verbose_name='訂單數量'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='訂單狀態'),
        ),
    ]
