# Generated by Django 5.0.4 on 2024-07-12 07:34

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='產品種類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='種類描述')),
                ('user', common.models.BaseUserForeignKey(blank=True, db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', '銷售中'), ('out_of_stock', '缺貨中'), ('discontinued', '停售')], default='available', max_length=20, verbose_name='訂單狀態')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='產品名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='產品描述')),
                ('price', models.IntegerField(blank=True, default=1, verbose_name='產品價格')),
                ('stock', models.PositiveIntegerField(blank=True, verbose_name='產品庫存')),
                ('user', common.models.BaseUserForeignKey(blank=True, db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
