# Generated by Django 5.0.4 on 2024-08-22 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('available', '銷售中'), ('out_of_stock', '缺貨中'), ('discontinued', '停售')], default='out_of_stock', max_length=20, verbose_name='訂單狀態')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='產品名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='產品描述')),
                ('price', models.IntegerField(blank=True, default=1, verbose_name='產品價格')),
                ('stock', models.IntegerField(blank=True, default=0, verbose_name='產品庫存')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='產品種類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='種類描述')),
                ('color', models.CharField(blank=True, default='#000000', max_length=10, verbose_name='色塊')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
    ]
