# Generated by Django 5.0.4 on 2024-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=10, verbose_name='色塊'),
        ),
    ]
