# Generated by Django 5.0.4 on 2024-08-15 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_unique_product_name_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_category_name_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='unique_product_name_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'deleted_at'), name='unique_product_category_name_deleted_at'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('name', 'deleted_at'), name='unique_product_name_deleted_at'),
        ),
    ]
